const pieces = {
  black: {
    king: { pos: "D8", id: "dark-king", img: "../img/dark-king.png" },
    queen: { pos: "E8", id: "dark-queen", img: "../img/dark-queen.png" },
    bishop_1: { pos: "C8", id: "dark-bishop1", img: "../img/dark-bishop.png" },
    bishop_2: { pos: "F8", id: "dark-bishop2", img: "../img/dark-bishop.png" },
    knight_1: { pos: "B8", id: "dark-knight1", img: "../img/dark-knight.png" },
    knight_2: { pos: "G8", id: "dark-knight2", img: "../img/dark-knight.png" },
    rook_1: { pos: "A8", id: "dark-rook1", img: "../img/dark-rook.png" },
    rook_2: { pos: "H8", id: "dark-rook", img: "../img/dark-rook.png" },
    pawn_1: { pos: "A7", id: "dark-pawn1", img: "../img/dark-pawn.png" },
    pawn_2: { pos: "B7", id: "dark-pawn2", img: "../img/dark-pawn.png" },
    pawn_3: { pos: "C7", id: "dark-pawn3", img: "../img/dark-pawn.png" },
    pawn_4: { pos: "D7", id: "dark-pawn4", img: "../img/dark-pawn.png" },
    pawn_5: { pos: "E7", id: "dark-pawn5", img: "../img/dark-pawn.png" },
    pawn_6: { pos: "F7", id: "dark-pawn6", img: "../img/dark-pawn.png" },
    pawn_7: { pos: "G7", id: "dark-pawn7", img: "../img/dark-pawn.png" },
    pawn_8: { pos: "H7", id: "dark-pawn8", img: "../img/dark-pawn.png" },
  },
  white: {
    king: { pos: "D1", id: "light-king", img: "../img/light-king.png" },
    queen: { pos: "E1", id: "light-queen", img: "../img/light-queen.png" },
    bishop_1: {
      pos: "C1",
      id: "light-bishop1",
      img: "../img/light-bishop.png",
    },
    bishop_2: {
      pos: "F1",
      id: "light-bishop2",
      img: "../img/light-bishop.png",
    },
    knight_1: {
      pos: "B1",
      id: "light-knight1",
      img: "../img/light-knight.png",
    },
    knight_2: {
      pos: "G1",
      id: "light-knight2",
      img: "../img/light-knight.png",
    },
    rook_1: { pos: "A1", id: "light-rook1", img: "../img/light-rook.png" },
    rook_2: { pos: "H1", id: "light-rook", img: "../img/light-rook.png" },
    pawn_1: { pos: "A2", id: "light-pawn1", img: "../img/light-pawn.png" },
    pawn_2: { pos: "B2", id: "light-pawn2", img: "../img/light-pawn.png" },
    pawn_3: { pos: "C2", id: "light-pawn3", img: "../img/light-pawn.png" },
    pawn_4: { pos: "D2", id: "light-pawn4", img: "../img/light-pawn.png" },
    pawn_5: { pos: "E2", id: "light-pawn5", img: "../img/light-pawn.png" },
    pawn_6: { pos: "F2", id: "light-pawn6", img: "../img/light-pawn.png" },
    pawn_7: { pos: "G2", id: "light-pawn7", img: "../img/light-pawn.png" },
    pawn_8: { pos: "H2", id: "light-pawn8", img: "../img/light-pawn.png" },
  },
};
