const pieces = [
  // black pieces
  { pos: "D8", id: "dark-king", name: "king", img: "../img/dark-king.png" },
  { pos: "E8", id: "dark-queen", name: "queen", img: "../img/dark-queen.png" },
  {
    pos: "C8",
    id: "dark-bishop1",
    name: "bishop",
    img: "../img/dark-bishop.png",
  },
  {
    pos: "F8",
    id: "dark-bishop2",
    name: "bishop",
    img: "../img/dark-bishop.png",
  },
  {
    pos: "B8",
    id: "dark-knight1",
    name: "knight",
    img: "../img/dark-knight.png",
  },
  {
    pos: "G8",
    id: "dark-knight2",
    name: "knight",
    img: "../img/dark-knight.png",
  },
  { pos: "A8", id: "dark-rook1", name: "rook", img: "../img/dark-rook.png" },
  { pos: "H8", id: "dark-rook", name: "rook", img: "../img/dark-rook.png" },
  { pos: "A7", id: "dark-pawn1", name: "pawn", img: "../img/dark-pawn.png" },
  { pos: "B7", id: "dark-pawn2", name: "pawn", img: "../img/dark-pawn.png" },
  { pos: "C7", id: "dark-pawn3", name: "pawn", img: "../img/dark-pawn.png" },
  { pos: "D7", id: "dark-pawn4", name: "pawn", img: "../img/dark-pawn.png" },
  { pos: "E7", id: "dark-pawn5", name: "pawn", img: "../img/dark-pawn.png" },
  { pos: "F7", id: "dark-pawn6", name: "pawn", img: "../img/dark-pawn.png" },
  { pos: "G7", id: "dark-pawn7", name: "pawn", img: "../img/dark-pawn.png" },
  { pos: "H7", id: "dark-pawn8", name: "pawn", img: "../img/dark-pawn.png" },
  // white pieces
  { pos: "D1", id: "light-king", name: "king", img: "../img/light-king.png" },
  {
    pos: "E1",
    id: "light-queen",
    name: "queen",
    img: "../img/light-queen.png",
  },
  {
    pos: "C1",
    id: "light-bishop1",
    name: "bishop",
    img: "../img/light-bishop.png",
  },
  {
    pos: "F1",
    id: "light-bishop2",
    name: "bishop",
    img: "../img/light-bishop.png",
  },
  {
    pos: "B1",
    id: "light-knight1",
    name: "knight",
    img: "../img/light-knight.png",
  },
  {
    pos: "G1",
    id: "light-knight2",
    name: "knight",
    img: "../img/light-knight.png",
  },
  { pos: "A1", id: "light-rook1", name: "rook", img: "../img/light-rook.png" },
  { pos: "H1", id: "light-rook", name: "rook", img: "../img/light-rook.png" },
  { pos: "A2", id: "light-pawn1", name: "pawn", img: "../img/light-pawn.png" },
  { pos: "B2", id: "light-pawn2", name: "pawn", img: "../img/light-pawn.png" },
  { pos: "C2", id: "light-pawn3", name: "pawn", img: "../img/light-pawn.png" },
  { pos: "D2", id: "light-pawn4", name: "pawn", img: "../img/light-pawn.png" },
  { pos: "E2", id: "light-pawn5", name: "pawn", img: "../img/light-pawn.png" },
  { pos: "F2", id: "light-pawn6", name: "pawn", img: "../img/light-pawn.png" },
  { pos: "G2", id: "light-pawn7", name: "pawn", img: "../img/light-pawn.png" },
  { pos: "H2", id: "light-pawn8", name: "pawn", img: "../img/light-pawn.png" },
];

export default pieces;
