const pieces = [
  // black pieces
  { pos: "D8", id: "black-king", name: "king", img: "../img/black-king.png" },
  {
    pos: "E8",
    id: "black-queen",
    name: "queen",
    img: "../img/black-queen.png",
  },
  {
    pos: "C8",
    id: "black-bishop1",
    name: "bishop",
    img: "../img/black-bishop.png",
  },
  {
    pos: "F8",
    id: "black-bishop2",
    name: "bishop",
    img: "../img/black-bishop.png",
  },
  {
    pos: "B8",
    id: "black-knight1",
    name: "knight",
    img: "../img/black-knight.png",
  },
  {
    pos: "G8",
    id: "black-knight2",
    name: "knight",
    img: "../img/black-knight.png",
  },
  { pos: "A8", id: "black-rook1", name: "rook", img: "../img/black-rook.png" },
  { pos: "H8", id: "black-rook", name: "rook", img: "../img/black-rook.png" },
  { pos: "A7", id: "black-pawn1", name: "pawn", img: "../img/black-pawn.png" },
  { pos: "B7", id: "black-pawn2", name: "pawn", img: "../img/black-pawn.png" },
  { pos: "C7", id: "black-pawn3", name: "pawn", img: "../img/black-pawn.png" },
  { pos: "D7", id: "black-pawn4", name: "pawn", img: "../img/black-pawn.png" },
  { pos: "E7", id: "black-pawn5", name: "pawn", img: "../img/black-pawn.png" },
  { pos: "F7", id: "black-pawn6", name: "pawn", img: "../img/black-pawn.png" },
  { pos: "G7", id: "black-pawn7", name: "pawn", img: "../img/black-pawn.png" },
  { pos: "H7", id: "black-pawn8", name: "pawn", img: "../img/black-pawn.png" },
  // white pieces
  { pos: "D1", id: "white-king", name: "king", img: "../img/white-king.png" },
  {
    pos: "E1",
    id: "white-queen",
    name: "queen",
    img: "../img/white-queen.png",
  },
  {
    pos: "C1",
    id: "white-bishop1",
    name: "bishop",
    img: "../img/white-bishop.png",
  },
  {
    pos: "F1",
    id: "white-bishop2",
    name: "bishop",
    img: "../img/white-bishop.png",
  },
  {
    pos: "B1",
    id: "white-knight1",
    name: "knight",
    img: "../img/white-knight.png",
  },
  {
    pos: "G1",
    id: "white-knight2",
    name: "knight",
    img: "../img/white-knight.png",
  },
  { pos: "A1", id: "white-rook1", name: "rook", img: "../img/white-rook.png" },
  { pos: "H1", id: "white-rook", name: "rook", img: "../img/white-rook.png" },
  { pos: "A2", id: "white-pawn1", name: "pawn", img: "../img/white-pawn.png" },
  { pos: "B2", id: "white-pawn2", name: "pawn", img: "../img/white-pawn.png" },
  { pos: "C2", id: "white-pawn3", name: "pawn", img: "../img/white-pawn.png" },
  { pos: "D2", id: "white-pawn4", name: "pawn", img: "../img/white-pawn.png" },
  { pos: "E2", id: "white-pawn5", name: "pawn", img: "../img/white-pawn.png" },
  { pos: "F2", id: "white-pawn6", name: "pawn", img: "../img/white-pawn.png" },
  { pos: "G2", id: "white-pawn7", name: "pawn", img: "../img/white-pawn.png" },
  { pos: "H2", id: "white-pawn8", name: "pawn", img: "../img/white-pawn.png" },
];

export default pieces;
